---
- hosts: localhost
  gather_facts: no
  vars:
    env_dir: "{{ env | default('k8s_kind') }}"
    base_path: "../../../{{ env_dir }}"
  tasks:
    - name: "Iniciando deploy no ambiente: {{ env_dir }}"
      debug:
        msg: "Aplicando manifestos de {{ base_path }}"

    - name: Add Kubecost Helm Chart
      ansible.builtin.command:
        helm repo add kubecost https://kubecost.github.io/kubecost/
      register: output1
      ignore_errors: yes

    - name: Verificar a saída do output1
      debug:
        var: output1.stdout_lines
      ignore_errors: yes

    - name: Helm repo update
      ansible.builtin.command:
        helm repo update
      register: output2
      ignore_errors: yes

    - name: Verificar a saída do output2
      debug:
        var: output2.stdout_lines
      ignore_errors: yes

    - name: Install or Upgrade Kubecost Helm Chart
      ansible.builtin.command:
        helm upgrade --install kubecost kubecost/kubecost -n kubecost -f values/kubecost-values.yaml
      register: output3
      ignore_errors: yes

    - name: Verificar a saída do output3
      debug:
        var: output3.stdout_lines
      ignore_errors: yes

    - name: Apply Kubecost Manifests (HTTPRoute and HealthCheckPolicy)
      ansible.builtin.command:
        kubectl apply -f {{ base_path }}/kubecost/
      register: output4
      ignore_errors: yes

    - name: Verificar a saída do output4
      debug:
        var: output4.stdout_lines
      ignore_errors: yes