apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: aiops-engine-hc-policy
  namespace: aiops
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        port: 8000
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: aiops-engine
