apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aiops

resources:
  - rollout.yaml
  - rbac.yaml
  - service.yaml
  - health-check.yaml
  - service_account.yaml

labels:
  - includeSelectors: true
    pairs:
      app: aiops-engine

images:
  - name: aiops-engine
    newName: southamerica-east1-docker.pkg.dev/naconfeitaria/artreg-aiops/aiops
    newTag: latest
