# 1. Componente Crítico: Ativa o cluster Redis de Alta Disponibilidade
redis-ha:
  enabled: true
redis:
  enabled: false

# 2. Configurações do Servidor Web/API
server:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  extraArgs:
    - --insecure

# 3. Configurações do Servidor de Repositórios Git
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5

# 4. Configuração do Application Controller
controller:
  # O Controller padrão não escala horizontalmente sem configurar "sharding". 
  # Manter 1 réplica é o padrão seguro na maioria dos cenários inicias de HA.
  replicas: 2
  pdb:
    enabled: true
    minAvailable: 1