livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 5
  timeoutSeconds: 3
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 5
  timeoutSeconds: 3
mode: "deployment"

fullnameOverride: "opentelemetry-collector"

replicaCount: 1

image:
  repository: "otel/opentelemetry-collector-contrib"

serviceMonitor:
  enabled: true
  additionalLabels:
    release: monitoring

extraEnvs:
  - name: NEW_RELIC_LICENSE_KEY
    valueFrom:
      secretKeyRef:
        name: newrelic-api-key
        key: NEW_RELIC_APIKEY

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    protocol: TCP
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
  health-check:
    enabled: true
    containerPort: 13133
    servicePort: 13133
    protocol: TCP

config:
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
      timeout: 5s
      send_batch_size: 1024
      send_batch_max_size: 2048
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

  exporters:
    prometheusremotewrite:
      endpoint: "http://monitoring-kube-prometheus-prometheus.monitoring-ns.svc.cluster.local:9090/api/v1/write"
      resource_to_telemetry_conversion:
        enabled: true

    otlphttp/loki:
      endpoint: "http://loki-gateway.monitoring-ns.svc.cluster.local:80/otlp"
      tls:
        insecure: true

    otlp/newrelic:
      endpoint: "otlp.nr-data.net:4317"
      headers:
        api-key: ${env:NEW_RELIC_LICENSE_KEY}

    debug:
      verbosity: normal
      sampling_initial: 5
      sampling_thereafter: 200

  service:
    extensions: [health_check]
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [prometheusremotewrite, otlp/newrelic, debug]
      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlphttp/loki, debug]
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlp/newrelic, debug]