resources:
  operator:
    requests:
      cpu: 16m
      memory: 64Mi
      
  metricServer:
    requests:
      cpu: 16m
      memory: 64Mi
      
  webhooks:
    requests:
      cpu: 16m
      memory: 32Mi