apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-engine-application
  namespace: argocd
  labels:
    app: aiops-engine
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:rhuanlasoares/fiap-tech-challenge05.git
    targetRevision: main
    path: k8s/aiops
  destination:
    server: https://kubernetes.default.svc
    namespace: aiops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
