apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-service-hc-policy
  namespace: argocd
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
