apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: donation-ns

resources:
- analysis-template.yaml
- configmap.yaml
- rollout.yaml
- health-check.yaml
- keda.yaml
- init-db.yaml
- netpol.yaml
- pdb.yaml
- secret.yaml
- service_account.yaml
- service.yaml
- trigger_authentication.yaml

labels:
- includeSelectors: true
  pairs:
    app: donation-service

images:
- name: donation-service
  newName: southamerica-east1-docker.pkg.dev/naconfeitaria/artreg-donation-sa/donation-service
  newTag: 60dd012379eb62a02fd3fee5406e3311345c6c50
