---
apiVersion: v1
kind: Secret
metadata:
  name: donation-secrets
  namespace: donation-ns
type: Opaque
stringData:
  PORT: "8082"
  AWS_REGION: us-east-1
  DB_PORT: "5432"
  CLOUDSQL_CONNECTION_NAME: ces-igniteprogram:southamerica-east1:sql-rhuan-donation
  CLOUDSQL_CONNECTION_NAME_REPLICA: ces-igniteprogram:us-east1:sql-rhuan-donation-replica
  DB_HOST: "127.0.0.1"
  DB_USER: "devops"
  DB_NAME: "donation_db"