apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-service
  namespace: ngo-ns
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  selector:
    matchLabels:
      app: ngo-service
  template:
    metadata:
      labels:
        app: ngo-service
    spec:
      serviceAccountName: sa-gke
      initContainers:
        - name: cloud-sql-proxy
          restartPolicy: Always
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
          args:
            - "--private-ip"
            - "--port=$(DB_PORT)"
            - "$(CLOUDSQL_CONNECTION_NAME)"
          env:
            - name: CLOUDSQL_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: ngo-secrets-job
                  key: CLOUDSQL_CONNECTION_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: ngo-secrets
                  key: DB_PORT
          securityContext:
            runAsNonRoot: true
      containers:
        - name: ngo-service
          image: ngo-service:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            periodSeconds: 10
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            periodSeconds: 10
            initialDelaySeconds: 15
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: ngo-secrets
                  key: PORT
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "opentelemetry-collector.monitoring-ns.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=ngo-ns,deployment.environment=production,service.name=ngo-service"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_SERVICE_NAME
              value: "ngo-service"
          resources:
            requests:
              cpu: 16m
              memory: 32Mi
            limits:
              cpu: 64m
              memory: 128Mi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: ngo-service