apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ngo-ns

resources:
- analysis-template.yaml
- configmap.yaml
- rollout.yaml
- health-check.yaml
- hpa.yaml
- init-db.yaml
- netpol.yaml
- pdb.yaml
- secret.yaml
- service_account.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    app: ngo-service

images:
- name: ngo-service
  newName: southamerica-east1-docker.pkg.dev/naconfeitaria/artreg-ngo-sa/ngo-service
  newTag: 60dd012379eb62a02fd3fee5406e3311345c6c50
