---
apiVersion: v1
kind: Secret
metadata:
  name: ngo-secrets
  namespace: ngo-ns
type: Opaque
stringData:
  PORT: "8081"
  DB_PORT: "5432"
  CLOUDSQL_CONNECTION_NAME: ces-igniteprogram:southamerica-east1:sql-rhuan-ngo
  CLOUDSQL_CONNECTION_NAME_REPLICA: ces-igniteprogram:us-east1:sql-rhuan-ngo-replica
  DB_HOST: "127.0.0.1"
  DB_USER: "devops"
  DB_NAME: "ngo_db"