---
apiVersion: v1
kind: Secret
metadata:
  name: volunteer-secrets
  namespace: volunteer-ns
type: Opaque
stringData:
  PORT: "8083"
  AWS_REGION: us-east-1
  AWS_DYNAMODB_TABLE: SolidaryTech2
