---
apiVersion: v1
kind: Secret
metadata:
  name: job-secrets
  namespace: job-ns
type: Opaque
stringData:
  PROJECT_ID: ces-igniteprogram
  REGION_GCP: southamerica-east1
  DB_USER: devops
  DB_PORT: "5432"
  DB_NGO_NAME: ngo_db
  DB_DONATION_NAME: donation_db
  NGO_DB_SECRET_MANAGER: sm-ngo-db
  DONATION_DB_SECRET_MANAGER: sm-donation-db
  NAME_SM_ACCESS_KEY_ID: sm-aws-access-key-id
  NAME_SM_SECRET_ACCESS_KEY: sm-aws-secret-access-key
  NAME_SM_SESSION_TOKEN: sm-aws-session-token
  NAME_SM_SQS_QUEUE_URL: sm-sqs-queue-url
  NEW_RELIC_APIKEY: sm-newrelic-apikey
  GEMINI_API_KEY: sm-gemini-api-key
  SLACK_WEBHOOK_URL: sm-webhook-slack