---
apiVersion: batch/v1
kind: Job
metadata:
  name: secrets-setup-job
  namespace: job-ns
spec:
  template:
    spec:
      serviceAccountName: sa-gke
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-namespaces
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "⏳ Aguardando os namespaces serem criados..."
              until kubectl get ns donation-ns && kubectl get ns ngo-ns && kubectl get ns volunteer-ns && kubectl get ns monitoring-ns && kubectl get ns aiops; do
                echo "⏳ Namespaces ainda não estão prontos. Tentando novamente em 5 segundos..."
                sleep 5
              done
              echo "✅ Todos os namespaces foram encontrados!"
      containers:
        - name: secret-manager-extractor
          image: google/cloud-sdk:alpine
          command:
            - /bin/sh
            - -c
            - |
              # Instalar o kubectl dentro da imagem do gcloud
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              mv kubectl /usr/local/bin/

              echo "🔐 Extraindo segredos do Google Secret Manager..."

              # ─────────────────────────────────────────────────────────────
              # Extrai dados do Secret Manager
              # ─────────────────────────────────────────────────────────────
              NGO_DB_SECRET_MANAGER=$(gcloud secrets versions access latest --secret=$NGO_DB_SECRET_MANAGER)
              DONATION_DB_SECRET_MANAGER=$(gcloud secrets versions access latest --secret=$DONATION_DB_SECRET_MANAGER)
              AWS_KEY_ID=$(gcloud secrets versions access latest --secret=$NAME_SM_ACCESS_KEY_ID)
              AWS_SECRET=$(gcloud secrets versions access latest --secret=$NAME_SM_SECRET_ACCESS_KEY)
              SQS_URL=$(gcloud secrets versions access latest --secret=$NAME_SM_SQS_QUEUE_URL)
              NEW_RELIC_APIKEY=$(gcloud secrets versions access latest --secret=$NEW_RELIC_APIKEY)
              GEMINI_API_KEY=$(gcloud secrets versions access latest --secret=$GEMINI_API_KEY)
              SLACK_WEBHOOK_URL=$(gcloud secrets versions access latest --secret=$SLACK_WEBHOOK_URL)
              # ─────────────────────────────────────────────────────────────

              kubectl create secret generic donation-secrets-job -n donation-ns \
                --from-literal=DB_PASSWORD="$DONATION_DB_SECRET_MANAGER" \
                --from-literal=DATABASE_URL="postgres://$DB_USER:$DONATION_DB_SECRET_MANAGER@127.0.0.1:$DB_PORT/$DB_DONATION_NAME?sslmode=disable" \
                --from-literal=AWS_ACCESS_KEY_ID="$AWS_KEY_ID" \
                --from-literal=AWS_SECRET_ACCESS_KEY="$AWS_SECRET" \
                --from-literal=AWS_SQS_QUEUE_URL="$SQS_URL" \
                --from-literal=NEW_RELIC_APIKEY="$NEW_RELIC_APIKEY"
              echo "🔐 Donation Secrets criados com sucesso!"

              kubectl create secret generic ngo-secrets-job -n ngo-ns \
                --from-literal=DB_PASSWORD="$NGO_DB_SECRET_MANAGER" \
                --from-literal=DATABASE_URL="postgres://$DB_USER:$NGO_DB_SECRET_MANAGER@127.0.0.1:$DB_PORT/$DB_NGO_NAME?sslmode=disable" \
                --from-literal=NEW_RELIC_APIKEY="$NEW_RELIC_APIKEY"
              echo "🔐 NGO Secrets criados com sucesso!"

              kubectl create secret generic volunteer-secrets-job -n volunteer-ns \
                --from-literal=AWS_ACCESS_KEY_ID="$AWS_KEY_ID" \
                --from-literal=AWS_SECRET_ACCESS_KEY="$AWS_SECRET" \
                --from-literal=NEW_RELIC_APIKEY="$NEW_RELIC_APIKEY"
              echo "🔐 Volunteer Secrets criados com sucesso!"

              kubectl create secret generic newrelic-api-key -n monitoring-ns \
                --from-literal=NEW_RELIC_APIKEY="$NEW_RELIC_APIKEY"
              echo "🔐 New Relic Secrets criados com sucesso!"

              kubectl create secret generic api-keys -n aiops \
                --from-literal=GEMINI_API_KEY="$GEMINI_API_KEY" \
                --from-literal=SLACK_WEBHOOK_URL="$SLACK_WEBHOOK_URL"
              echo "🔐 API Keys Secrets criados com sucesso!"

              echo "🚀 Setup concluído com sucesso!"
          env:
            - name: PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: PROJECT_ID
            - name: REGION_GCP
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: REGION_GCP
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: DB_USER
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: DB_PORT
            - name: DB_NGO_NAME
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: DB_NGO_NAME
            - name: DB_DONATION_NAME
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: DB_DONATION_NAME
            - name: NGO_DB_SECRET_MANAGER
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: NGO_DB_SECRET_MANAGER
            - name: DONATION_DB_SECRET_MANAGER
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: DONATION_DB_SECRET_MANAGER
            - name: NAME_SM_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: NAME_SM_ACCESS_KEY_ID
            - name: NAME_SM_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: NAME_SM_SECRET_ACCESS_KEY
            - name: NAME_SM_SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: NAME_SM_SQS_QUEUE_URL
            - name: NEW_RELIC_APIKEY
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: NEW_RELIC_APIKEY
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: GEMINI_API_KEY
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: job-secrets
                  key: SLACK_WEBHOOK_URL